district: West Valley-Mission Community College District
baseUrl: https://go.boarddocs.com/ca/wvm/Board.nsf
cutoffDate: "20200317"

site:
  title: West Valley-Mission Public Meetings
  description: Agendas, minutes, and agenda attachments for public governing meetings.
  output: docs
  bondExpenditures: data/wvm-bond-expenditures.json

committees:
  board:
    name: Board of Trustees
    id: A4EP6J588C05
    output: data/wvm-board-of-trustees-boarddocs.json
  cboc:
    name: Citizens' Bond Oversight Committee
    id: AXGUFA70206A
    output: data/wvm-cboc-boarddocs.json
