name = "rcsd-data"
main = "index.js"
compatibility_date = "2024-09-25"

routes = [
  { pattern = "data.rcsd.info/*", zone_name = "rcsd.info" }
]

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "rcsd-meetings"
